bootstrap.servers=localhost:9092
topic.location=electric-vehicle-location
topic.evdata=electric-vehicle-evdata
csv.default.location=Electric_Vehicle_Location_Data.csv
csv.default.evdata=Electric_Vehicle_Data.csv
